### ISSUE TITLE
rtmidi AttributeError: 'module' object has no attribute 'API_UNSPECIFIED'

### ISSUE THREAD

**Issue by sparr** [tpneill/nanoKontroller#1]
```
Traceback (most recent call last):
  File "./nanoKontroller", line 307, in <module>
    inport = mido.open_input('nanoKONTROL2 MIDI 1')
  File "/home/sparr/.local/lib/python2.7/site-packages/mido/backends/backend.py", line 91, in open_input
    return self.module.Input(name, **self._add_api(kwargs))
  File "/home/sparr/.local/lib/python2.7/site-packages/mido/ports.py", line 161, in __init__
    BasePort.__init__(self, name, **kwargs)
  File "/home/sparr/.local/lib/python2.7/site-packages/mido/ports.py", line 86, in __init__
    self._open(**kwargs)
  File "/home/sparr/.local/lib/python2.7/site-packages/mido/backends/rtmidi.py", line 118, in _open
    rtapi = _get_api_id(api)
  File "/home/sparr/.local/lib/python2.7/site-packages/mido/backends/rtmidi.py", line 34, in _get_api_id
    return rtmidi.API_UNSPECIFIED
AttributeError: 'module' object has no attribute 'API_UNSPECIFIED'
```

not sure where to go from here to collect more info

**Comment by tpneill** [comment]
This is some odd case in having a slightly incorrect rtmidi library installed. The core mido library has a fix listed at https://github.com/mido/mido/issues/145
